### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by gann0001** [nicomon24/Sneks#4]
I am getting this error when i importing like below
import Sneks
import numpy as np
import gym
import random
env = gym.make('snek-v1')

KeyError: 'snek-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sumithkumargannarapu/Desktop/python/CS5033/Assignment2/hw2_Q2.py", line 8, in <module>
    env = gym.make('snek-v1')
  File "/anaconda3/lib/python3.6/site-packages/gym/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/anaconda3/lib/python3.6/site-packages/gym/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/anaconda3/lib/python3.6/site-packages/gym/gym/envs/registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: snek-v1

**Comment by gann0001** [comment]
Hello,

snek is working fine for me now. But I am writing Q learning using snek-v1 gym. Could you please help me to create state-space and Q table.

wondering about the dimensions of the Qtable

**Comment by nicomon24** [comment]
I'm closing the issue since the env is working fine.

Regarding your question, tabular Q-learning is certainly out of question in the snek environment (as it is, with the raw or rgb observation), since you would need to enumerate all the 16x16 possible images (not feasible). So, I suggest you choose an algorithm with an approximated Q-function (like DQN or similar) or you could "simplify" the environment, using as state only the current position of the snake and the one of the food. With this simplification you could apply tabular Q-learning, but your agent will be obviously less capable of learning because it does not "see" nothing but its head and the food.

If you have further questions of the kind, I suggest you ask some other place like 
[/r/reinforcementlearning](https://www.reddit.com/r/reinforcementlearning/)
or
[/r/learnmachinelearning](https://www.reddit.com/r/learnmachinelearning/)
